run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - internal/mocks
  skip-dirs-use-default: true
  skip-files: []
  print-resources-usage: true
  go: '1.22'
  show-stats: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # DEFAULT LINTERS
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    # - unused

    # OTHER LINTERS
    # - asasalint
    # - asciicheck
    # - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - copyloopvar
    - cyclop
    # - decorder
    # - depguard
    # - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    - errchkjson
    - errname
    # - errorlint
    # - execinquery
    - exhaustive
    # - exhaustruct
    # - exportloopref
    # - forbidigo
    - forcetypeassert
    - funlen
    - gci
    # - ginkgolinter
    # - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    # - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    # - gocyclo
    - godot
    # - godox
    # - goerr113
    - gofmt
    # - gofumpt
    # - goheader
    - goimports
    - gomnd
    - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    # - gosmopolitan
    # - grouper
    - importas
    # - inamedparam
    # - interfacebloat
    # - intrange
    - ireturn
    - lll
    # - loggercheck
    # - maintidx
    - makezero
    # - mirror
    # - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    # - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    # - nonamedreturns
    # - nosnakecase
    # - nosprintfhostport
    # - paralleltest
    - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    - reassign
    # - revive
    # - rowserrcheck
    - sloglint
    # - spancheck
    - sqlclosecheck
    - stylecheck
    # - tagalign
    # - tagliatelle
    - tenv
    # - testableexamples
    - testifylint
    - testpackage
    # - thelper
    - tparallel
    # - typecheck
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    # - whitespace
    # - wrapcheck
    - wsl
    # - zerologlint

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0.0
    skip-tests: true

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  errchkjson:
    check-error-free-encoding: false
    report-no-exported: false

  exhaustive:
    check: [ switch ]
    check-generated: false
    default-signifies-exhaustive: true
    ignore-enum-members: "Example.+"
    ignore-enum-types: "Example.+"
    package-scope-only: true
    default-case-required: false

  funlen:
    lines: 80
    statements: -1
    ignore-comments: true

  gci:
    sections:
      - standard                                  # Standard section: captures all standard packages.
      - default                                   # Default section: contains all imports that could not be matched to another section type.
      - blank                                     # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot                                       # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      # - alias                                     # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      - prefix(github.com/royhq/go-play-app)      # Custom section: groups all imports with the specified Prefix.

    skip-generated: true
    custom-order: true

  gocognit:
    min-complexity: 10

  goconst:
    min-len: 3
    min-occurrences: 2
    ignore-tests: true
    match-constant: true
    numbers: false
    min: 2
    max: 2
    ignore-calls: true
    ignore-strings: ""

  gocritic:
    # Checks: https://go-critic.com/overview
    enabled-checks:
      - nestingReduce
      - ruleguard
      - truncateCmp

      - appendAssign
      - argOrder
      - boolExprSimplify
      - commentedOutCode
      - deferUnlambda
      - emptyFallthrough
      - externalErrorReassign
      - httpNoBody
      - hugeParam
      - paramTypeCombine
      - rangeExprCopy
      - rangeValCopy

    settings:
      commentedOutCode:
        minLength: 10
      hugeParam:
        sizeThreshold: 80
      nestingReduce:
        bodyWidth: 5
      rangeExprCopy:
        sizeThreshold: 512
        skipTestFuncs: true
      rangeValCopy:
        sizeThreshold: 128
        skipTestFuncs: true
      truncateCmp:
        skipArchDependent: true

  gocyclo:
    min-complexity: 10

  godot:
    scope: toplevel
    exclude:
      # Exclude todo and fixme comments.
      - "^FIXME:"
      - "^TODO:"
    period: true
    capital: true

  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  goimports:
    local-prefixes: github.com/royhq/go-play-app

  gomnd:
    checks: ["argument", "case", "condition", "operation", "return", "assign"]
    ignored-numbers: []
    # List of file patterns to exclude from analysis.
    # Values always ignored: `.+_test.go`
    # Default: []
    ignored-files: []
    ignored-functions:
      - '^math\.'
      - '^http\.StatusText$'

  gomoddirectives:
    replace-local: false
    replace-allow-list: []
    retract-allow-no-explanation: false
    exclude-forbidden: false

  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    # Default: [] - means include all rules
    includes:
      - G101 # Look for hard coded credentials
      - G102 # Bind to all interfaces
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G108 # Profiling endpoint automatically exposed on /debug/pprof
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G111 # Potential directory traversal
      - G112 # Potential slowloris attack
      - G113 # Usage of Rat.SetString in math/big with an overflow (CVE-2022-23772)
      - G114 # Use of net/http serve function that has no support for setting timeouts
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G203 # Use of unescaped data in HTML templates
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G303 # Creating tempfile using a predictable path
      - G304 # File path provided as taint input
      - G305 # File traversal when extracting zip/tar archive
      - G306 # Poor file permissions used when writing to a new file
      - G307 # Poor file permissions used when creating a file with os.Create
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
      - G501 # Import blocklist: crypto/md5
      - G502 # Import blocklist: crypto/des
      - G503 # Import blocklist: crypto/rc4
      - G504 # Import blocklist: net/http/cgi
      - G505 # Import blocklist: crypto/sha1
      - G601 # Implicit memory aliasing of items from a range statement
      - G602 # Slice access out of bounds

    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    # Default: []
    excludes:
      - G101 # Look for hard coded credentials
      - G102 # Bind to all interfaces
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G108 # Profiling endpoint automatically exposed on /debug/pprof
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G111 # Potential directory traversal
      - G112 # Potential slowloris attack
      - G113 # Usage of Rat.SetString in math/big with an overflow (CVE-2022-23772)
      - G114 # Use of net/http serve function that has no support for setting timeouts
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G203 # Use of unescaped data in HTML templates
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G303 # Creating tempfile using a predictable path
      - G304 # File path provided as taint input
      - G305 # File traversal when extracting zip/tar archive
      - G306 # Poor file permissions used when writing to a new file
      - G307 # Poor file permissions used when creating a file with os.Create
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
      - G501 # Import blocklist: crypto/md5
      - G502 # Import blocklist: crypto/des
      - G503 # Import blocklist: crypto/rc4
      - G504 # Import blocklist: net/http/cgi
      - G505 # Import blocklist: crypto/sha1
      - G601 # Implicit memory aliasing of items from a range statement
      - G602 # Slice access out of bounds

    # Exclude generated files
    # Default: false
    exclude-generated: true

    # Filter out the issues with a lower severity than the given value.
    # Valid options are: low, medium, high.
    # Default: low
    severity: medium

    # Filter out the issues with a lower confidence than the given value.
    # Valid options are: low, medium, high.
    # Default: low
    confidence: medium

    # Concurrency value.
    # Default: the number of logical CPUs usable by the current process.
    concurrency: 12

    # To specify the configuration of rules.
    config:
      # Globals are applicable to all rules.
      global:
        # If true, ignore #nosec in comments (and an alternative as well).
        # Default: false
        nosec: true
        # Add an alternative comment prefix to #nosec (both will work at the same time).
        # Default: ""
        "#nosec": "#my-custom-nosec"
        # Define whether nosec issues are counted as finding or not.
        # Default: false
        show-ignored: true
        # Audit mode enables addition checks that for normal code analysis might be too nosy.
        # Default: false
        audit: true
      G101:
        # Regexp pattern for variables and constants to find.
        # Default: "(?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|cred"
        pattern: "(?i)example"
        # If true, complain about all cases (even with low entropy).
        # Default: false
        ignore_entropy: false
        # Maximum allowed entropy of the string.
        # Default: "80.0"
        entropy_threshold: "80.0"
        # Maximum allowed value of entropy/string length.
        # Is taken into account if entropy >= entropy_threshold/2.
        # Default: "3.0"
        per_char_threshold: "3.0"
        # Calculate entropy for first N chars of the string.
        # Default: "16"
        truncate: "32"
      # Additional functions to ignore while checking unhandled errors.
      # Following functions always ignored:
      #   bytes.Buffer:
      #     - Write
      #     - WriteByte
      #     - WriteRune
      #     - WriteString
      #   fmt:
      #     - Print
      #     - Printf
      #     - Println
      #     - Fprint
      #     - Fprintf
      #     - Fprintln
      #   strings.Builder:
      #     - Write
      #     - WriteByte
      #     - WriteRune
      #     - WriteString
      #   io.PipeWriter:
      #     - CloseWithError
      #   hash.Hash:
      #     - Write
      #   os:
      #     - Unsetenv
      # Default: {}
      G104:
        fmt:
          - Fscanf
      G111:
        # Regexp pattern to find potential directory traversal.
        # Default: "http\\.Dir\\(\"\\/\"\\)|http\\.Dir\\('\\/'\\)"
        pattern: "custom\\.Dir\\(\\)"
      # Maximum allowed permissions mode for os.Mkdir and os.MkdirAll
      # Default: "0750"
      G301: "0750"
      # Maximum allowed permissions mode for os.OpenFile and os.Chmod
      # Default: "0600"
      G302: "0600"
      # Maximum allowed permissions mode for os.WriteFile and ioutil.WriteFile
      # Default: "0600"
      G306: "0600"

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
      shadow:
        strict: false
      unusedresult:
        funcs:
        stringmethods: []

    disable-all: true
    enable:
      - appends
      # - asmdecl
      - assign
      # - atomic
      # - atomicalign
      - bools
      # - buildtag
      - cgocall
      # - composites
      - copylocks
      - deepequalerrors
      - defers
      # - directive
      - errorsas
      # - fieldalignment
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - reflectvaluecompare
      - shadow
      - shift
      - sigchanyzer
      - slog
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite

    enable-all: false

  grouper:
    const-require-single-const: false
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: false
    type-require-single-type: false
    type-require-grouping: false
    var-require-single-var: false
    var-require-grouping: false

  importas:
    no-unaliased: true
    no-extra-aliases: false
    alias: []

  interfacebloat:
    max: 5

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - (or|er)$

    reject: []

  lll:
    line-length: 120
    tab-width: 1

  makezero:
    always: false

  musttag:
    functions: []

  nakedret:
    max-func-lines: 20

  nestif:
    min-complexity: 5

  nolintlint:
    allow-unused: true
    allow-no-explanation: [ ]
    require-explanation: true
    require-specific: true

  paralleltest:
    ignore-missing: true
    ignore-missing-subtests: true

  perfsprint:
    int-conversion: false
    err-error: true
    errorf: true
    sprintf1: false
    strconcat: false

  prealloc:
    # IMPORTANT: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.
    simple: true
    range-loops: true
    for-loops: true

  reassign:
    patterns: ["EOF", "Err.*"]

  sloglint:
    no-mixed-args: true
    kv-only: false
    attr-only: false
    context-only: true
    static-msg: true
    no-raw-keys: false
    key-naming-case: snake
    args-on-sep-lines: false

  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["all"]

  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist: []
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]
    # http-status-code-whitelist: ["200", "400", "404", "500"]

  tenv:
    all: false

  testifylint:
    # Checkers: https://github.com/Antonboom/testifylint#checkers
    enable-all: false
    disable-all: true
    enable:
      - blank-import
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - go-require
      - float-compare
      - len
      - nil-compare
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call
      - suite-thelper
      - useless-assert
    expected-actual:
      pattern: (^(exp(ected)?|want(ed)?)([A-Z]\w*)?$)|(^(\w*[a-z])?(Exp(ected)?|Want(ed)?)$)
    require-error:
      fn-pattern: ^(Errorf?|NoErrorf?)$

  testpackage:
    skip-regexp: (export|internal)_test\.go
    allow-packages: ["main"]

  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: false
    tls-signature-scheme: false
    constant-kind: false

  unparam:
    check-exported: true

  unused:
    field-writes-are-uses: true
    post-statements-are-reads: true
    exported-is-used: false
    exported-fields-are-used: false
    parameters-are-used: false
    local-variables-are-used: false
    generated-is-used: true

  varnamelen:
    max-distance: 6
    min-name-length: 2
    check-receiver: false
    check-return: false
    check-type-param: false
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
    ignore-decls:
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - m map[string]int
      - w http.ResponseWriter
      - w io.Writer
      - r *http.Request

  whitespace:
    multi-if: true
    multi-func: true

  wsl:
    # Configurations: https://github.com/bombsimon/wsl/blob/master/doc/configuration.md
    strict-append: true
    allow-assign-and-call: true
    allow-assign-and-anything: false
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    force-case-trailing-whitespace: 0
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-err-cuddling: true
    force-short-decl-cuddling: false
    allow-cuddle-with-calls: ["Lock", "RLock"]
    allow-cuddle-with-rhs: ["Unlock", "RUnlock"]
    error-variable-names: ["err"]

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  # https://golangci-lint.run/usage/false-positives/#default-exclusions
  include: []
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  new-from-rev: ""
  new-from-patch: ""
  fix: false
  whole-files: false

severity:
  default-severity: ""
  case-sensitive: true
  rules: []