with-expecter: true
dir: "./internal/mocks"
filename: "mock_{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}Mock"
outpkg: "mocks"

packages:
  github.com/royhq/go-play-app/features/users/create:
    interfaces:
      UserInserter:
