version: '3.8'

services:

  db:
    image: postgres
    container_name:  play-app-db-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: play-app-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

